services:
  database:
    image: postgres:16.3-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgress-storage/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin1234
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=traumdb
    
  web:
    build: ./
    ports:
      - 3001:3001
      - 8282:8282
    depends_on:
      - database
    links:
      - database